# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainView.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 238)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MainPage_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.MainPage_tab.setObjectName("MainPage_tab")
        self.tab_a1 = QtWidgets.QWidget()
        self.tab_a1.setObjectName("tab_a1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_a1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.initA1MainPage_button = QtWidgets.QPushButton(self.tab_a1)
        self.initA1MainPage_button.setObjectName("initA1MainPage_button")
        self.verticalLayout.addWidget(self.initA1MainPage_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.FillA1MainPage_button = QtWidgets.QPushButton(self.tab_a1)
        self.FillA1MainPage_button.setCheckable(False)
        self.FillA1MainPage_button.setDefault(False)
        self.FillA1MainPage_button.setFlat(False)
        self.FillA1MainPage_button.setObjectName("FillA1MainPage_button")
        self.verticalLayout.addWidget(self.FillA1MainPage_button)
        self.FillNextPersonForm_button = QtWidgets.QPushButton(self.tab_a1)
        self.FillNextPersonForm_button.setObjectName("FillNextPersonForm_button")
        self.verticalLayout.addWidget(self.FillNextPersonForm_button)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.MainPage_tab.addTab(self.tab_a1, "")
        self.tab_copy_summary = QtWidgets.QWidget()
        self.tab_copy_summary.setObjectName("tab_copy_summary")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_copy_summary)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.initSummaryMainPage_button = QtWidgets.QPushButton(self.tab_copy_summary)
        self.initSummaryMainPage_button.setObjectName("initSummaryMainPage_button")
        self.verticalLayout_2.addWidget(self.initSummaryMainPage_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.SummaryFileName_line = QtWidgets.QLineEdit(self.tab_copy_summary)
        self.SummaryFileName_line.setText("Naujausia-kom.-suvestinė-2019m.xlsx")
        self.SummaryFileName_line.setObjectName("SummaryFileName_line")
        self.verticalLayout_2.addWidget(self.SummaryFileName_line)
        self.SummaryMonth_dropdown = QtWidgets.QComboBox(self.tab_copy_summary)
        self.SummaryMonth_dropdown.setMaxVisibleItems(12)
        self.SummaryMonth_dropdown.setObjectName("SummaryMonth_dropdown")
        self.SummaryMonth_dropdown.addItem("")
        self.SummaryMonth_dropdown.addItem("")
        self.SummaryMonth_dropdown.addItem("")
        self.SummaryMonth_dropdown.addItem("")
        self.SummaryMonth_dropdown.addItem("")
        self.SummaryMonth_dropdown.addItem("")
        self.SummaryMonth_dropdown.addItem("")
        self.SummaryMonth_dropdown.addItem("")
        self.SummaryMonth_dropdown.addItem("")
        self.SummaryMonth_dropdown.addItem("")
        self.SummaryMonth_dropdown.addItem("")
        self.SummaryMonth_dropdown.addItem("")
        self.verticalLayout_2.addWidget(self.SummaryMonth_dropdown)
        self.SummaryCopy_button = QtWidgets.QPushButton(self.tab_copy_summary)
        self.SummaryCopy_button.setObjectName("SummaryCopy_button")
        self.verticalLayout_2.addWidget(self.SummaryCopy_button)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.MainPage_tab.addTab(self.tab_copy_summary, "")
        self.horizontalLayout.addWidget(self.MainPage_tab)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 420, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.MainPage_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.MainPage_tab, self.FillA1MainPage_button)
        MainWindow.setTabOrder(self.FillA1MainPage_button, self.FillNextPersonForm_button)
        MainWindow.setTabOrder(self.FillNextPersonForm_button, self.SummaryFileName_line)
        MainWindow.setTabOrder(self.SummaryFileName_line, self.SummaryMonth_dropdown)
        MainWindow.setTabOrder(self.SummaryMonth_dropdown, self.SummaryCopy_button)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AutomateDocs"))
        self.initA1MainPage_button.setText(_translate("MainWindow", "Pradėti"))
        self.FillA1MainPage_button.setToolTip(_translate("MainWindow", "Užpildyti naujos A1 formos pradinį puslapį"))
        self.FillA1MainPage_button.setText(_translate("MainWindow", "Užpildyti A1 pradinį puslapį"))
        self.FillNextPersonForm_button.setToolTip(_translate("MainWindow", "Pridėkite naują anketą o tada paspauskite kad jį būtų užpildyta su sekančio asmens informacija"))
        self.FillNextPersonForm_button.setText(_translate("MainWindow", "Užpildyti sekantčio asmens anketą"))
        self.MainPage_tab.setTabText(self.MainPage_tab.indexOf(self.tab_a1), _translate("MainWindow", "A1 pildymas"))
        self.initSummaryMainPage_button.setText(_translate("MainWindow", "Pradėti"))
        self.SummaryMonth_dropdown.setItemText(0, _translate("MainWindow", "Sausis"))
        self.SummaryMonth_dropdown.setItemText(1, _translate("MainWindow", "Vasaris"))
        self.SummaryMonth_dropdown.setItemText(2, _translate("MainWindow", "Kovas"))
        self.SummaryMonth_dropdown.setItemText(3, _translate("MainWindow", "Balandis"))
        self.SummaryMonth_dropdown.setItemText(4, _translate("MainWindow", "Gegužė"))
        self.SummaryMonth_dropdown.setItemText(5, _translate("MainWindow", "Birželis"))
        self.SummaryMonth_dropdown.setItemText(6, _translate("MainWindow", "Liepa"))
        self.SummaryMonth_dropdown.setItemText(7, _translate("MainWindow", "Rugpjūtis"))
        self.SummaryMonth_dropdown.setItemText(8, _translate("MainWindow", "Rugsėjis"))
        self.SummaryMonth_dropdown.setItemText(9, _translate("MainWindow", "Spalis"))
        self.SummaryMonth_dropdown.setItemText(10, _translate("MainWindow", "Lapkritis"))
        self.SummaryMonth_dropdown.setItemText(11, _translate("MainWindow", "Gruodis"))
        self.SummaryCopy_button.setText(_translate("MainWindow", "Nukopijuoti duomenis į sekantį mėnesį"))
        self.MainPage_tab.setTabText(self.MainPage_tab.indexOf(self.tab_copy_summary), _translate("MainWindow", "Suvestinės pildymas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
